refactor cmd import_students and move code to separate package `ugentstudent`
ugent-library/old-people-service pull request #48
Opened 2023-09-01 12:35 UTC by nicolasfranck

fixes #40 

Notes:

- moved all code importing students to separate package `ugentstudent`
- will do that rewrite of `other_id` in a separate PR

2023-09-01 14:30 UTC, netsensei requested changes

2023-09-01 14:30 UTC, netsensei commented on cli/import_students_cmd.go
> +	"github.com/ugent-library/people-service/ugentstudent"
No need to call it "ugentstudent" since we won't have students from other institutions. Just `student` is enough.

2023-09-01 14:30 UTC, netsensei commented on ugentstudent/ugentstudent.go
> +		/*
Do we need to keep this comment? It's kind of stating the obvious, no?

2023-09-01 14:30 UTC, netsensei commented on ugentstudent/ugentstudent.go
> +		//TODO: use modifytimestamp to fetch records incrementally?
Turn this todo into a discussion

2023-09-01 14:30 UTC, netsensei commented on ugentstudent/ugentstudent.go
> +				return fmt.Errorf("unable to update person: %w", err)
What happens if this error conditions is triggered? Does it break the loop / importing? Or does the import continue?

Maybe you want to make the `cb` callback accept errors as well so you can pass them to the logger?

2023-09-01 14:30 UTC, netsensei commented on ugentstudent/ugentstudent.go
> +				return fmt.Errorf("unable to create person: %w", err)
What happens if this error conditions is triggered? Does it break the loop / importing? Or does the import continue?

Maybe you want to make the cb callback accept errors as well so you can pass them to the logger?

2023-09-01 14:34 UTC, nicolasfranck commented on ugentstudent/ugentstudent.go
> +		/*
agreed

2023-09-01 14:34 UTC, nicolasfranck commented on cli/import_students_cmd.go
> +	"github.com/ugent-library/people-service/ugentstudent"
agreed

2023-09-01 14:36 UTC, nicolasfranck commented on ugentstudent/ugentstudent.go
> +		/*
I keep this to avoid confusion about the output. It is returning object of type models.Person, so one could have the impression that these come from the database.

2023-09-01 14:51 UTC, nicolasfranck commented on ugentstudent/ugentstudent.go
> +		//TODO: use modifytimestamp to fetch records incrementally?
https://github.com/ugent-library/people-service/discussions/50

2023-09-01 14:57 UTC, nicolasfranck commented on ugentstudent/ugentstudent.go
> +				return fmt.Errorf("unable to update person: %w", err)
yes it breaks the loop, and the error is eventually returned as error from SearchPeople.

the callback in ImportAll does not need an error, as it only calls the callback when a record is successfully imported.

2023-09-04 07:59 UTC, nicolasfranck commented on cli/import_students_cmd.go
> +	"github.com/ugent-library/people-service/ugentstudent"
done

2023-09-04 09:08 UTC, nicolasfranck commented on ugentstudent/ugentstudent.go
> +		/*
ok, I have made `ugentldap.SearchPeople` a bit more raw, and let it return a `ldap.Entry`.
Mapping to a `models.Person` is now done in the client code.
I had to change `gismo/gismo.go` I am afraid, but that was rather limited,
as we do not copy a lot of ldap information.

2023-09-05 08:41 UTC, merged